apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-service-pvc
spec:
    resources:
        requests:
            storage: 200Mi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteMany