apiVersion: apps/v1
kind: Deployment
metadata:
    name: machine-learning-service-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: machine-learning-service-depl
    template:
        metadata:
            labels:
                app: machine-learning-service-depl
        spec:
            containers:
                - name: machine-learning-service-depl
                  image: leviis/idarch-machine-learning-service:1.0.0
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5000
                  env:
                      - name: DB_HOST
                        value: <db-host>
                      - name: DB_NAME
                        value: idarch_machine_learning_service
                      - name: DB_USERNAME
                        value: postgres
                      - name: DB_PASSWORD
                        value: <db-password>
                      - name: DB_PORT
                        value: "5432"
                      - name: FLASK_ENV
                        value: production
                      - name: SQLALCHEMY_TRACK_MODIFICATIONS
                        value: "False"
                      - name: LOG_LEVEL
                        value: "WARNING"
