apiVersion: apps/v1
kind: Deployment
metadata:
    name: main-service-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: main-service-depl
    template:
        metadata:
            labels:
                app: main-service-depl
        spec:
            containers:
                - name: main-service-depl
                  image: leviis/idarch-main-service:1.0.0
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  env:
                      - name: SERVER_PORT
                        value: "8080"
                      - name: DB_HOST
                        value: <db-host>
                      - name: DB_PORT
                        value: "5432"
                      - name: DB_NAME
                        value: idarch_main_service
                      - name: DB_USERNAME
                        value: postgres
                      - name: DB_PASSWORD
                        value: <db-password>
