apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-service-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo-service-depl
    template:
        metadata:
            labels:
                app: mongo-service-depl
        spec:
            containers:
                - name: mongo-service-depl
                  image: mongo:8.0.9
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        value: mongo
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        value: password
                      - name: MONGO_INITDB_DATABASE
                        value: idarch_machine_learning_service
                  volumeMounts:
                      - mountPath: /data/db
                        name: mongo-service-pvc
            volumes:
                - name: mongo-service-pvc
                  persistentVolumeClaim:
                      claimName: mongo-service-pvc
