apiVersion: v1
kind: Service
metadata:
    name: db-service-ci
spec:
    type: ClusterIP
    selector:
        app: db-service-depl
    ports:
        - port: 5432
          targetPort: 5432
          protocol: TCP