apiVersion: v1
kind: Service
metadata:
    name: mongo-service-np.yml
spec:
    type: NodePort
    selector:
        app: mongo-service-depl
    ports:
        - port: 27017
          targetPort: 27017
