apiVersion: v1
kind: Service
metadata:
    name: mongo-service-ci
spec:
    type: ClusterIP
    selector:
        app: mongo-service-depl
    ports:
        - port: 27017
          targetPort: 27017
          protocol: TCP